# Generated by Django 4.0 on 2022-03-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=240, verbose_name='name')),
                ('email', models.CharField(max_length=240, unique=True, verbose_name='email')),
                ('mobile', models.CharField(max_length=240, unique=True, verbose_name='mobile')),
                ('password', models.CharField(max_length=240, verbose_name='password')),
            ],
        ),
    ]
