# Generated by Django 4.0 on 2022-03-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=240, verbose_name='name')),
                ('email', models.CharField(max_length=240, unique=True, verbose_name='email')),
                ('mobile', models.CharField(max_length=240, unique=True, verbose_name='mobile')),
                ('password', models.CharField(max_length=240, verbose_name='password')),
                ('ipaddr', models.CharField(default='0.0.0.0', max_length=50, verbose_name='ipaddress')),
                ('createdOn', models.DateTimeField(blank=True, null=True, verbose_name='createdon')),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
