# Generated by Django 4.0 on 2022-03-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customers_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(verbose_name='subId')),
                ('cusID', models.IntegerField(verbose_name='cusId')),
                ('planCode', models.CharField(max_length=50, verbose_name='plancode')),
                ('startDate', models.DateTimeField(verbose_name='startdate')),
                ('endDate', models.DateTimeField(verbose_name='endDate')),
                ('isActive', models.BooleanField(verbose_name='isactive')),
                ('createdOn', models.DateTimeField(verbose_name='createdon')),
                ('createdMode', models.CharField(choices=[('1', 'Online'), ('2', 'Offline')], max_length=20, verbose_name='createdmode')),
                ('createdBy', models.CharField(choices=[('1', 'Manual'), ('2', 'Online')], max_length=20, verbose_name='createdby')),
                ('payMode', models.CharField(max_length=1, verbose_name='paymode')),
                ('payNarration', models.CharField(max_length=500, verbose_name='paynarration')),
                ('comments', models.CharField(max_length=500, verbose_name='comments')),
            ],
        ),
    ]
